;Returns a ConfigParser object with the default 'shrec-default' section.
;does what get_default_shrec_config did

[shrec-default]
name = shrec
dataset = origin
data_root = /content/data
cnn_spec_ss = ds100
cnn_spec_vs = ds100
n_epochs = 30
epoch_list = 20
test_mode = test
;v square images size;square images size v
inputWH = 100 